{
	"info": {
		"_postman_id": "3afd66e8-c28e-434c-9c2e-97d382fac69b",
		"name": "test-kredit-plus",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "users",
			"item": [
				{
					"name": "Register User/Customer, using form-data for upload ktp,selfie,checking_account",
					"request": {
						"method": "POST",
						"header": [
							{
								"warning": "This is a duplicate header and will be overridden by the Content-Type header generated by Postman.",
								"key": "Content-Type",
								"value": "multipart/form-data",
								"type": "text"
							}
						],
						"body": {
							"mode": "formdata",
							"formdata": [
								{
									"key": "nik",
									"value": "3175070705990001",
									"type": "text"
								},
								{
									"key": "email",
									"value": "rijal1@gmail.com",
									"type": "text"
								},
								{
									"key": "salary",
									"value": "8000000",
									"type": "text"
								},
								{
									"key": "birth_place",
									"value": "jakarta",
									"type": "text"
								},
								{
									"key": "birth_date",
									"value": "07-05-1999",
									"type": "text"
								},
								{
									"key": "ktp",
									"type": "file",
									"src": "/C:/Users/Arul/Downloads/FakhrulMRijal (1) (1).jpg"
								},
								{
									"key": "selfie",
									"type": "file",
									"src": "/C:/Users/Arul/Downloads/FakhrulMRijal (1).jpg"
								},
								{
									"key": "rek_koran",
									"type": "file",
									"src": "/C:/Users/Arul/Downloads/ATE-FM-HR&GA-01-04 Applicant Data Form (2) (1).pdf"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								},
								{
									"key": "rek_koran",
									"type": "file",
									"src": "/C:/Users/Arul/OneDrive/Pictures/britech_podcast_ui_ux.jpg"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/users/register",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"users",
								"register"
							]
						}
					},
					"response": []
				},
				{
					"name": "Login User/Customer,  that return access_token",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "email",
									"value": "rijal1@gmail.com",
									"type": "text"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/users/login",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"users",
								"login"
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "employees",
			"item": [
				{
					"name": "Register Employees,",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "email",
									"value": "employee1@gmail.com",
									"type": "text"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								},
								{
									"key": "username",
									"value": "employee1",
									"type": "text"
								},
								{
									"key": "role",
									"value": "admin",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/employees/register",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"employees",
								"register"
							]
						}
					},
					"response": []
				},
				{
					"name": "Login Employees, that return access token for give decision expends average User/Customer",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "email",
									"value": "employee1@gmail.com",
									"type": "text"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/employees/login",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"employees",
								"login"
							]
						}
					},
					"response": []
				},
				{
					"name": "Update expend average user Authorization using Bearer, that with access token admin role by employees",
					"request": {
						"auth": {
							"type": "bearer",
							"bearer": [
								{
									"key": "token",
									"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtcGxveWVlMUBnbWFpbC5jb20iLCJpZCI6MX0.uD6oQI6vNcf-LuWPsYUp4HsyO5h8dj0l33NDf7LK6pc",
									"type": "string"
								}
							]
						},
						"method": "PUT",
						"header": [
							{
								"key": "",
								"value": "",
								"type": "text",
								"disabled": true
							}
						],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "expend_average",
									"value": "3000000",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/users/1",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"users",
								"1"
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "goodOwners",
			"item": [
				{
					"name": "Register GoodOwners",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "email",
									"value": "xyz1@gmail.com",
									"type": "text"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								},
								{
									"key": "name",
									"value": "xyz",
									"type": "text",
									"disabled": true
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/goodsOwners/register",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"goodsOwners",
								"register"
							]
						}
					},
					"response": []
				},
				{
					"name": "Good owners login that return access token, for create goods from goodsOwners",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "email",
									"value": "xyz1@gmail.com",
									"type": "text"
								},
								{
									"key": "password",
									"value": "1234567",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/goodsOwners/login",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"goodsOwners",
								"login"
							]
						}
					},
					"response": []
				},
				{
					"name": "Create Goods By AccessToken GoodOwners",
					"request": {
						"auth": {
							"type": "bearer",
							"bearer": [
								{
									"key": "token",
									"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inh5ejFAZ21haWwuY29tIiwiaWQiOjEsInJvbGUiOiJnb29kLW93bmVycyJ9.xx29KNmKVAyrkO6u84qDMGjFaJP6d3bx-GhY47KRGdE",
									"type": "string"
								}
							]
						},
						"method": "POST",
						"header": [],
						"body": {
							"mode": "urlencoded",
							"urlencoded": [
								{
									"key": "name",
									"value": "xyz Brand 2",
									"type": "text"
								},
								{
									"key": "price",
									"value": "5500000",
									"type": "text"
								},
								{
									"key": "rate",
									"value": "10",
									"type": "text"
								}
							]
						},
						"url": {
							"raw": "http://localhost:8080/goods",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"goods"
							]
						}
					},
					"response": []
				}
			]
		},
		{
			"name": "installments",
			"item": [
				{
					"name": "Create Installment with params goods slug, loan limit id & query select month authorize access token user/customer",
					"request": {
						"auth": {
							"type": "bearer",
							"bearer": [
								{
									"key": "token",
									"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpamFsMUBnbWFpbC5jb20iLCJpZCI6MSwicm9sZSI6ImN1c3RvbWVyIn0.0_5kqd0S7xoEzZDPj-Vb8-2fMEkHtKKkT8q4L9ZFF0U",
									"type": "string"
								}
							]
						},
						"method": "POST",
						"header": [],
						"url": {
							"raw": "http://localhost:8080/installments/1/xyz-brand-1?select_month=first_month",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "8080",
							"path": [
								"installments",
								"1",
								"xyz-brand-1"
							],
							"query": [
								{
									"key": "select_month",
									"value": "first_month"
								}
							]
						}
					},
					"response": []
				}
			]
		}
	]
}
